### ISSUE TITLE
How can I install the tool?

### ISSUE THREAD

**Issue by n350071** [jokester/worriedly#12]
Thank you for creating the cool tool 🎉
I wish I could try to use it.
But I don't know how to install it.
Could you write the instruction in the README?

**Comment by jokester** [comment]
Hello.

I feel sorry to say, the only working version for now is a web UI at https://worriedly.ihate.work/ .

A CLI version too (to make it easier for offline usage) is on the map. If it sounds interesting, you can watch this repo for future releases.

**Comment by n350071** [comment]
Hello, Jokester!

Thank you for replying.
I've turned on the watching status. I'm looking forward to it ;)
